### PR TITLE
Add support for the "status" command.

### PR DESCRIPTION
**Pull request by woodruffw**
This patch adds support for VLC's `status` command, which is useful for actually getting the path/URI to the media being played.

I put it in `MediaControls`, but I can move it to another module if you'd like.

Thanks for the awesome library!

### CODE REVIEW

**Comment by mguinada** [comment]
Thanks for your PR @woodruffw. 

The location at `MediaControls` is perfect and this is indeed a useful command, but I would rather have it output a hash with the keys: `:file`, `:volume` and `:state` than a vector. This is so we can be consistent with the [VLC::Client::PlaylistControls#playlist](https://github.com/mguinada/vlc-client/blob/master/lib/vlc-client/client/playlist_controls.rb#L52-L62) output.

If you want to make the change and [squash your commits](http://blog.steveklabnik.com/posts/2012-11-08-how-to-squash-commits-in-a-github-pull-request)  keeping just this one, I'll merge and release a new version right after I'm able solve the issues with the CI :)

**Comment by woodruffw** [comment]
> The location at MediaControls is perfect and this is indeed a useful command, but I would rather have it output a hash with the keys: :file, :volume and :state than a vector. This is so we can be consistent with the VLC::Client::PlaylistControls#playlist output.

No problem! I'll squash that into this PR in a bit.

**Comment by woodruffw** [comment]
Updated the commit.

I turned `STATUS_REGEXES` into `STATUS_MAPPING` and used some zip/map/hash magic to transfer its keys over to the matched expressions. Let me know if that's too obfuscated - I can make it return in a fashion similar to `PlaylistControls#playlist` instead :smile:

**Comment by mguinada** [comment]
Great! Released as v0.0.7.

**Comment by woodruffw** [comment]
Thanks so much!

**Pull request merged**
